import 'package:shri_ram_mandir/models/bhajan_model.dart';
import 'package:shri_ram_mandir/models/event_model.dart';

class Lists {
  static List<Event> eventDetails = [
    Event(id: "1928", title: "1928: Construction Babri Masjid", imageUrls: ["assets/images/1928.1.jpeg", "assets/images/1928.2.jpeg"], description: "The year 1528 is associated with the construction of the Babri Masjid in Ayodhya, Uttar Pradesh. According to historical accounts, it is believed that Mir Baqi, a general of the Mughal emperor Babur, constructed the Babri Masjid on the site where some Hindus believe Lord Ram was born. The construction of the Babri Masjid in 1528 is a key event in the history of the disputed site in Ayodhya. The Babri Masjid stood for centuries until its demolition in 1992, which triggered widespread communal tensions and led to a protracted legal battle over the ownership of the land.", year: 1928),
    Event(id: "1949", title: "1949: Idol Placement", imageUrls: ["assets/images/1949.1.png"], description: "The incident in 1949 is known as the placing of idols inside the Babri Masjid in Ayodhya. It played a significant role in the history of the disputed site where the Babri Masjid once stood. Here are the details:In December 1949, idols of Lord Ram appeared inside the central dome of the Babri Masjid in Ayodhya. The circumstances surrounding the appearance of these idols remain unclear, and the event led to tensions between the Hindu and Muslim communities. Following the placement of the idols, the local administration took control of the site and locked its gates. The matter was taken to court, leading to legal disputes over the ownership and rights to worship at the site. The locking of the gates was seen as an attempt to maintain peace and prevent communal tensions.", year: 1949),
    Event(id: "1950", title: "1950: Gopal Singh Visharad's Petition", imageUrls: ["assets/images/1950.jpeg"], description: "In December 1949, idols of Lord Ram mysteriously appeared inside the central dome of the Babri Masjid in Ayodhya. The circumstances surrounding how the idols were placed remain a subject of historical debate. The appearance of the idols led to increased tensions between the Hindu and Muslim communities. The site was subsequently locked, and the administration took control to prevent any potential conflicts. The locking of the site's gates was an attempt to maintain peace and prevent communal tensions. This event marked the beginning of legal disputes over the ownership and rights to worship at the site.", year: 1950),
    Event(id: "1961", title: "1961: Sunni Waqf Board's Case", imageUrls: ["assets/images/1961.1.jpeg", "assets/images/1961.2.jpg"], description: "There isn't a specific notable incident related to the Ayodhya Ram Janmabhoomi-Babri Masjid dispute in 1961. The legal and political disputes surrounding the site continued during this period, with various legal cases being filed by different parties. The legal battles over the possession of the Babri Masjid site were ongoing, and tensions persisted between the Hindu and Muslim communities. It wasn't until later developments, including the 1984 VHP movement and the 1986 unlocking of the Babri Masjid, that the issue gained significant national attention. If there is a specific aspect or event from 1961 you are referring to, please provide more details, and I will do my best to offer relevant information.", year: 1961),
    Event(id: "1984", title: "1984: VHP Movement Begins", imageUrls: ["assets/images/1984.1.jpg", "assets/images/1984.jpeg"], description: "In 1984, the Vishwa Hindu Parishad (VHP), a Hindu nationalist organization, launched a movement advocating for the construction of a Ram temple at the disputed site in Ayodhya. This movement marked a significant turning point in the long-standing Ayodhya Ram Janmabhoomi-Babri Masjid dispute", year: 1984),
    Event(id: "1986", title: "1986: Locks Opened", imageUrls: ["assets/images/default.jpg"], description: "The unlocking of the Babri Masjid set the stage for heightened communal tensions and intensified the Ayodhya dispute. The decision had long-term implications and contributed to the escalation of the conflict leading up to the demolition of the Babri Masjid in 1992. The events surrounding the Babri Masjid and the Ayodhya dispute have had a lasting impact on Indian politics and society.", year: 1986),
    Event(id: "1989", title: "1989: Foundation Ceremony", imageUrls: ["assets/images/default.jpg"], description: "The foundation ceremony in 1989 further heightened tensions and brought the Ayodhya dispute to the forefront of national attention. The call for the construction of the Ram temple became a rallying point for Hindu nationalist sentiments, and it set the stage for subsequent events, including the Ram Rath Yatra in 1990 and the eventual demolition of the Babri Masjid in 1992. The Ayodhya dispute continued to be a contentious issue in Indian politics and society.", year: 1989),
    Event(id: "1990", title: "1990: Ram Rath Yatra", imageUrls: ["assets/images/1990.1.jpg"], description: "The Ram Rath Yatra played a crucial role in bringing the Ayodhya dispute to the forefront of national politics. It galvanized support for the construction of a Ram temple and contributed to the political discourse surrounding the issue. The events of 1990 set the stage for subsequent developments, including the demolition of the Babri Masjid in 1992.", year: 1990),
    Event(id: "1992", title: "1992: Babri Masjid Demolition", imageUrls: ["assets/images/default.jpg"], description: "The Babri Masjid demolition marked a watershed moment in Indian history, intensifying religious and communal divides. The event triggered legal consequences, including the establishment of the Liberhan Commission to investigate the circumstances surrounding the demolition. The Ayodhya dispute became a defining issue in Indian politics and remained a source of contention for many years.", year: 1992),
    Event(id: "2002", title: "2002: ASI Excavation", imageUrls: ["assets/images/default.jpg"], description: "description", year: 2002),
    Event(id: "2010", title: "2010: Allahabad High Court Verdict", imageUrls: ["assets/images/default.jpg"], description: "description", year: 2010),
    Event(id: "2011", title: "2011: Supreme Court Stay", imageUrls: ["assets/images/default.jpg"], description: "description", year: 2011),
    Event(id: "2019", title: "2019 - November: Supreme Court Verdict", imageUrls: ["assets/images/default.jpg"], description: "description", year: 2019),
    Event(id: "2020", title: "2020 - August: Groundbreaking Ceremony", imageUrls: ["assets/images/default.jpg"], description: "description", year: 2020),
    Event(id: "2022", title: "2022 - January: Ongoing Construction", imageUrls: ["assets/images/default.jpg"], description: "description", year: 2022),
    Event(id: "2024", title: "2024 - Consecration ceremony", imageUrls: ["assets/images/2024.1.jpeg", "assets/images/2024.2.jpeg"], description: "Despite the construction of some wings still pending, the Ram temple is consecrated. A large ceremony featuring prominent figures, Hindu spiritual leaders, and Modi is held in Ayodhya. The ceremony involves a procession of idols and a statue of Ram being placed in the inner sanctum of the building. The temple will open to the public and devotees from Tuesday.", year: 2024),
  ];

  static List<Bhajan> bhajans = [
    Bhajan(title: "Hanuman Chalisa", description: "Gulshan Kumar", url: "assets/music/Hanuman Chalisa.mp3", coverUrl: "assets/images/shri_ram.png"),
    Bhajan(title: "Hum katha sunate Ram sakal", description: "Unknown artist", url: "assets/music/Hum katha sunate Ram sakal.mp3", coverUrl: "assets/images/shri_ram.png"),
    Bhajan(title: "Humare saath Shri Raghuath", description: "Pujya Krishnapriyaji", url: "assets/music/Humare Saath Shri Raghunath.mp3", coverUrl: "assets/images/Humare Saath Shri Raghunath.jpg"),
    Bhajan(title: "Ram Dhun", description: "Shankar Mahadevan", url: "assets/music/Ram Dhun.mp3", coverUrl: "assets/images/Ram Dhun.jpg"),
    Bhajan(title: "Shree Ramraksha Stotra", description: "Anuradha Paudwal", url: "assets/music/Shree Ramraksha Stotra.mp3", coverUrl: "assets/images/Shree Ramraksha Stotra.jpg")
  ];
}